- name: Create ACME challenge directory
  ansible.builtin.file:
    path: /var/www/certbot
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Configure ACME
  ansible.builtin.template:
    src: acme.conf.j2
    dest: /etc/nginx/conf.d/acme.conf
    mode: '0644'
  notify: Reload Nginx

- name: Validate Nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false