- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - gnupg
      - python3-setuptools
    state: latest
    update_cache: true

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Add Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Install Docker Module for Python
  apt:
    name: python3-docker
    state: present

- name: Install docker compose
  apt:
    name: docker-compose-plugin
    state: present
    cache_valid_time: 86400

- name: Add user to docker group
  user:
    name: deployer
    groups: docker
    append: yes

- name: Create project directory
  file:
    path: /opt/lab
    state: directory
    mode: 0755

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/lab/docker-compose.yml
    mode: 0644

- name: Configure Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /opt/lab/nginx.conf
    mode: 0644

- name: Create logs dir
  file:
    path: /opt/lab/logs
    state: directory
    mode: 0755

- name: Create uploads dir
  file:
    path: /opt/lab/uploads
    state: directory
    mode: 0755

- name: Install Logrotate
  apt:
    name: logrotate
    state: present

- name: Create logrotate config for lab logs
  ansible.builtin.template:
    src: templates/logrotate.conf.j2
    dest: /etc/logrotate.d/lab
    mode: 0644
  become: true

- name: Create .env file
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/lab/.env
    owner: deployer
    group: deployer
    mode: 0600

- name: Create Docker network 'production'
  docker_network:
    name: production
    driver: bridge

- name: Pull, down, and up docker-compose
  shell: |
    docker compose pull
    docker compose down --remove-orphans
    docker compose up -d
  args:
    chdir: /opt/lab/
  become: true

- name: Run database migrations
  shell: |
    docker compose exec -T app bundle exec rails db:create db:migrate
  args:
    chdir: /opt/lab/
  become: true
