source "https://rubygems.org"

gem "rails"
gem "pg"
gem "puma"
gem "redis"
gem "sidekiq"
gem "sidekiq-scheduler"
gem "prometheus_exporter"

gem "jbuilder"
gem "jwt"
gem "pundit"
gem "rack-attack"

gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
end
